---
title: "Final Project Critique"
author: "Shafi Rubbani"
date: "3/28/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Richard Qiu: Visualization of effects of Medicaid expansion on immunization rates
https://rqiu.shinyapps.io/Vaccine-Explorer/

Richard explored how the expansion of Medicaid through Obamacare impacted public health in the United States by analyzing trends in vaccinations. I like Richard's project because it is very straightforward. The relationship he is studying is very well-defined, and his data is well-suited to answer his questions. The animated plot does a good job of showing change over time. However, I wish there were trendlines or descriptions of how strong the trends are and what further implications this might have.

## Junho Moon: Looking at key military data of different countries over time
https://junhomoon.shinyapps.io/world_military/

Junho created an app that allows us to compare the militaries of different nations. He focused on personnel, arms, spending, and nuclear arms, and his apps show how military strength/focus changes over time. I really like how clearly Junho's plots show change and comparison. I think the website would be particularly useful in discussions of 20th century wars. I do wish there were more explanation of how he handled the data and what conclusions he drew.